"""Add info JSON column to Circuit table

Revision ID: 8f9e8f678033
Revises: cbdfd5ecaea7
Create Date: 2024-12-29 15:19:57.464883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f9e8f678033'
down_revision: Union[str, None] = 'cbdfd5ecaea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circuits', sa.Column('info', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('circuits', 'info')
    # ### end Alembic commands ###
