"""Add GIN index on info column in Circuits table

Revision ID: acc9dd8fe128
Revises: 8f9e8f678033
Create Date: 2024-12-29 19:36:25.163195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc9dd8fe128'
down_revision: Union[str, None] = '8f9e8f678033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.execute("CREATE INDEX idx_gin_info ON circuits USING GIN ((info::text) gin_trgm_ops);")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX idx_gin_info;")
    # ### end Alembic commands ###
