"""Removed tier

Revision ID: cbdfd5ecaea7
Revises: abc578b347d7
Create Date: 2024-12-28 14:55:14.908370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbdfd5ecaea7'
down_revision: Union[str, None] = 'abc578b347d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('circuits', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('circuits', 'location',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('circuits', 'length',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('circuits', 'laps',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('circuits', 'lap_record',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_index(op.f('ix_circuits_circuit_id'), 'circuits', ['circuit_id'], unique=False)
    op.alter_column('drivers', 'number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('drivers', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('drivers', 'nationality',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('drivers', 'team',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('drivers', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_index(op.f('ix_drivers_driver_id'), 'drivers', ['driver_id'], unique=False)
    op.drop_column('drivers', 'tier')
    op.alter_column('races', 'place',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('races', 'points',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('races', 'is_fastest_lap',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('races', 'start_place',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('races', 'start_place',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('races', 'is_fastest_lap',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('races', 'points',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('races', 'place',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('drivers', sa.Column('tier', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_drivers_driver_id'), table_name='drivers')
    op.alter_column('drivers', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('drivers', 'team',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('drivers', 'nationality',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('drivers', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('drivers', 'number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_circuits_circuit_id'), table_name='circuits')
    op.alter_column('circuits', 'lap_record',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('circuits', 'laps',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('circuits', 'length',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('circuits', 'location',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('circuits', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
